add: the make run_test in job of run_test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -53,10 +53,10 @@ jobs:
       image: epitechcontent/epitest-docker
     steps:
       - name: Checkout Repository 
-        run: action/checkout@v4
+        uses:  actions/checkout@v4
       
       - name: make tests_run 
-        run: timeout 120 make || {echo "Run test faild or timeout"; exit 1;}
+        run: timeout 120 make tests_run || {echo "Run test faild or timeout"; exit 1;}
   
   push_to_mirror:
       runs-on: ubuntu-latest
